// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// FinalizeAssertion implements finalizeAssertion operation.
//
// Finalize Assertion.
//
// POST /assertion
func (UnimplementedHandler) FinalizeAssertion(ctx context.Context, req OptFinalizeAssertionRequest) (r FinalizeAssertionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FinalizeAttestation implements finalizeAttestation operation.
//
// Finalize Attestation.
//
// POST /attestatoin
func (UnimplementedHandler) FinalizeAttestation(ctx context.Context, req FinalizeAttestationReq, params FinalizeAttestationParams) (r FinalizeAttestationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InitializeAssertion implements initializeAssertion operation.
//
// Initialize Assertion.
//
// GET /assertion
func (UnimplementedHandler) InitializeAssertion(ctx context.Context) (r InitializeAssertionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InitializeAttestation implements initializeAttestation operation.
//
// Initialize Attestation.
//
// GET /attestatoin
func (UnimplementedHandler) InitializeAttestation(ctx context.Context) (r InitializeAttestationRes, _ error) {
	return r, ht.ErrNotImplemented
}
