// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// FinalizeAttestationParams is parameters of finalizeAttestation operation.
type FinalizeAttestationParams struct {
	// Session.
	Session string
}

func unpackFinalizeAttestationParams(packed middleware.Parameters) (params FinalizeAttestationParams) {
	{
		key := middleware.ParameterKey{
			Name: "session",
			In:   "cookie",
		}
		params.Session = packed[key].(string)
	}
	return params
}

func decodeFinalizeAttestationParams(args [0]string, argsEscaped bool, r *http.Request) (params FinalizeAttestationParams, _ error) {
	c := uri.NewCookieDecoder(r)
	// Decode cookie: session.
	if err := func() error {
		cfg := uri.CookieParameterDecodingConfig{
			Name:    "session",
			Explode: true,
		}
		if err := c.HasParam(cfg); err == nil {
			if err := c.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Session = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "session",
			In:   "cookie",
			Err:  err,
		}
	}
	return params, nil
}
