// Code generated by ogen, DO NOT EDIT.
package api

type FinalizeAssertionRes interface {
	finalizeAssertionRes()
}

type FinalizeAttestationRes interface {
	finalizeAttestationRes()
}

type InitializeAssertionRes interface {
	initializeAssertionRes()
}

type InitializeAttestationJSONRes interface {
	initializeAttestationJSONRes()
}

type InitializeAttestationRes interface {
	initializeAttestationRes()
}
