// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// FinalizeAssertion implements finalizeAssertion operation.
	//
	// Finalize Assertion.
	//
	// POST /assertion
	FinalizeAssertion(ctx context.Context, req OptFinalizeAssertionRequest) (FinalizeAssertionRes, error)
	// FinalizeAttestation implements finalizeAttestation operation.
	//
	// Finalize Attestation.
	//
	// POST /attestatoin
	FinalizeAttestation(ctx context.Context, req FinalizeAttestationReq, params FinalizeAttestationParams) (FinalizeAttestationRes, error)
	// InitializeAssertion implements initializeAssertion operation.
	//
	// Initialize Assertion.
	//
	// GET /assertion
	InitializeAssertion(ctx context.Context) (InitializeAssertionRes, error)
	// InitializeAttestation implements initializeAttestation operation.
	//
	// Initialize Attestation.
	//
	// GET /attestatoin
	InitializeAttestation(ctx context.Context) (InitializeAttestationRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
